name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Lighthouse CI
        run: npm install && npm install -g @lhci/cli@0.8.x
      - name: Build
        run: |
          npm ci
          npm run build:ci
      - name: Run Lighthouse
        run: |
          lhci autorun
