name: Deploy to Firebase (preview)
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Clean
        run: |
          rm -rf ./dist/*
          rm -rf ./reports/*
          rm -rf ./coverage/*
          mkdir -p ./reports
      - name: Build Angular
        run: |
          npm install
          npm run build -- --base-href 'https://fem-readup--preview-t2lhpd7p.web.app'
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy preview
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
